# Generated by Django 3.2 on 2021-10-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_trip_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
