# Generated by Django 3.2 on 2021-10-12 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_adminmedia_booking_trip_usermedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermedia', to=settings.AUTH_USER_MODEL),
        ),
    ]
