# Generated by Django 3.2 on 2021-10-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_usermedia_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmedia',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adminmedia', to='database.trip'),
        ),
    ]
