# Generated by Django 3.2 on 2021-10-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_adminmedia_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin media/images'),
        ),
        migrations.AlterField(
            model_name='adminmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='admin media/videos'),
        ),
        migrations.AlterField(
            model_name='blogmedia',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/videos'),
        ),
    ]
