# Generated by Django 3.2 on 2021-10-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
