# Generated by Django 3.2 on 2021-10-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_adminmedia_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
