# Generated by Django 3.2 on 2021-10-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_tokens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tokens',
            new_name='WhitelistedTokens',
        ),
        migrations.AlterModelOptions(
            name='whitelistedtokens',
            options={'verbose_name_plural': 'WhitelistedTokens'},
        ),
    ]
