# Generated by Django 3.2 on 2021-10-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_blog_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='email',
        ),
    ]
