# Generated by Django 3.2 on 2021-10-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_rename_blogs_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
