# Generated by Django 3.2 on 2021-10-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20211028_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelistedtokens',
            options={'verbose_name_plural': 'Whitelisted Tokens'},
        ),
    ]
