# Generated by Django 3.2 on 2021-10-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20211016_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmedia',
            name='displayImage',
            field=models.BooleanField(default=False),
        ),
    ]
