# Generated by Django 3.2 on 2021-10-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_adminmedia_displayimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
