# Generated by Django 3.2 on 2021-10-29 10:52

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_whitelistedtokens_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelistedtokens',
            name='expiry',
            field=models.DateTimeField(default=database.models.WhitelistedTokens.now_plus_7),
        ),
    ]
