# Generated by Django 3.2 on 2021-10-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20211013_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='choice',
            field=models.CharField(choices=[('Booking', 'Booking'), ('Trip', 'Trip'), ('q3', 'Query 3'), ('q4', 'Query 4'), ('q5', 'Query 5'), ('other', 'Other')], max_length=50),
        ),
    ]
