# Generated by Django 3.2 on 2021-10-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_queries_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='choice',
            field=models.CharField(choices=[('q1', 'Booking'), ('q2', 'Trip'), ('q3', 'Query 3'), ('q4', 'Query 4'), ('q5', 'Query 5'), ('other', 'Other')], max_length=50),
        ),
    ]
