# Generated by Django 3.2 on 2021-11-01 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 0, 41, 20, 86887)),
        ),
    ]
