# Generated by Django 3.2 on 2021-11-01 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_booking_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 19, 11, 41, 22074, tzinfo=utc)),
        ),
    ]
