# Generated by Django 3.2 on 2021-10-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_rename_queries_query'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name_plural': 'Queries'},
        ),
        migrations.RenameField(
            model_name='query',
            old_name='Query',
            new_name='query',
        ),
    ]
