# Generated by Django 3.2 on 2021-10-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20211013_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
