# Generated by Django 3.2 on 2021-11-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_booking_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
