# Generated by Django 3.2 on 2021-10-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_review_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratings',
            field=models.IntegerField(choices=[(0, '0.5'), (1, '1'), (2, '1.5'), (3, 2), (4, '2.5'), (5, '3'), (6, '3.5'), (7, '4'), (8, '4.5'), (9, '5')]),
        ),
    ]
