# Generated by Django 3.2 on 2021-11-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_booking_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
