# Generated by Django 3.2 on 2021-11-24 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_trip_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerypagetemp',
            options={'verbose_name': 'GalleryPageTemp'},
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Temp',
            },
        ),
    ]
