# Generated by Django 3.2 on 2021-11-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20211125_0234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp',
            options={},
        ),
    ]
