# Generated by Django 3.2 on 2021-10-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_alter_review_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratings',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=3),
        ),
    ]
