# Generated by Django 3.2 on 2021-11-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_alter_blog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
