# Generated by Django 3.2 on 2021-10-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_alter_trip_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='Name',
            new_name='name',
        ),
    ]
