# Generated by Django 3.2 on 2022-01-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_alter_review_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='query',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
