# Generated by Django 3.2 on 2021-10-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_rename_explorepagetemp_gallerypagetemp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerypagetemp',
            options={'verbose_name': 'Temp'},
        ),
        migrations.AddField(
            model_name='gallerypagetemp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
