# Generated by Django 3.2 on 2022-02-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
