# Generated by Django 3.2 on 2021-10-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_auto_20211021_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='phoneNumber',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
