# Generated by Django 3.2 on 2021-10-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0037_query_phonenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Queries'},
        ),
    ]
