# Generated by Django 3.2 on 2022-08-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0037_alter_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='choice',
            field=models.CharField(choices=[('1', 'Booking'), ('2', 'Trip'), ('3', 'Query 4'), ('4', 'Query 5'), ('5', 'Other')], max_length=8),
        ),
    ]
