# Generated by Django 3.2 on 2022-08-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_alter_query_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypagetemp',
            name='userKey',
            field=models.CharField(max_length=100000),
        ),
    ]
