# Generated by Django 3.2 on 2021-10-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_alter_query_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name_plural': 'Queries'},
        ),
    ]
