# Generated by Django 3.2 on 2021-10-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0047_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='choice',
            field=models.CharField(choices=[('1', 'Booking'), ('2', 'Trip'), ('3', 'Query 3'), ('4', 'Query 4'), ('5', 'Query 5'), ('6', 'Other')], max_length=8),
        ),
    ]
